FROM python:3.9.1

# Installer les dépendances système nécessaires
RUN apt-get update && apt-get install -y wget

# Installer les dépendances Python
RUN pip install pandas sqlalchemy psycopg2 pyarrow

WORKDIR /app
COPY data-loading-parquet.py  data-loading-parquet.py

ENTRYPOINT [ "python", "data-loading-parquet.py" ]